// ------------------------------------------------------------------------
// RAL Test Package: timer_regs_regs_ral_test_pkg
// Auto-generated by AutoUVM RAL Sequence Generator
// ------------------------------------------------------------------------

package timer_regs_regs_ral_test_pkg;

    import uvm_pkg::*;
    `include "uvm_macros.svh"
    import timer_regs_regs_ral_pkg::*;

// ------------------------------------------------------------------------
// RAL Reset Value Test Sequence for timer_regs_regs
// ------------------------------------------------------------------------

class timer_regs_regs_reset_test_seq extends uvm_sequence;
    `uvm_object_utils(timer_regs_regs_reset_test_seq)

    timer_regs_regs_block reg_model;

    function new(string name = "timer_regs_regs_reset_test_seq");
        super.new(name);
    endfunction : new

    task body();
        uvm_status_e status;
        uvm_reg_data_t rdata;
        int errors = 0;

        `uvm_info(get_type_name(), "Starting reset value check...", UVM_LOW)

        // Check reset value of timer_cmp0_value_q (expected: 0x0)
        reg_model.timer_cmp0_value_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_cmp0_value_q: %s", status.name()))
            errors++;
        end else if (rdata !== 32'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_cmp0_value_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_cmp0_value_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of intr_q (expected: 0x0)
        reg_model.intr_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read intr_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("intr_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("intr_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_cmp1_value_q (expected: 0x0)
        reg_model.timer_cmp1_value_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_cmp1_value_q: %s", status.name()))
            errors++;
        end else if (rdata !== 32'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_cmp1_value_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_cmp1_value_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_cmp0_wr_q (expected: 0x0)
        reg_model.timer_cmp0_wr_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_cmp0_wr_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_cmp0_wr_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_cmp0_wr_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_val0_wr_q (expected: 0x0)
        reg_model.timer_val0_wr_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_val0_wr_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_val0_wr_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_val0_wr_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_ctrl0_enable_q (expected: 0x0)
        reg_model.timer_ctrl0_enable_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl0_enable_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_ctrl0_enable_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_ctrl0_enable_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of rvalid_q (expected: 0x0)
        reg_model.rvalid_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read rvalid_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("rvalid_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("rvalid_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_val1_wr_q (expected: 0x0)
        reg_model.timer_val1_wr_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_val1_wr_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_val1_wr_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_val1_wr_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of rd_data_q (expected: 0x0)
        reg_model.rd_data_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read rd_data_q: %s", status.name()))
            errors++;
        end else if (rdata !== 32'h0) begin
            `uvm_error(get_type_name(), $sformatf("rd_data_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("rd_data_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of wvalid_q (expected: 0x0)
        reg_model.wvalid_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read wvalid_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("wvalid_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("wvalid_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of wr_data_q (expected: 0x0)
        reg_model.wr_data_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read wr_data_q: %s", status.name()))
            errors++;
        end else if (rdata !== 32'h0) begin
            `uvm_error(get_type_name(), $sformatf("wr_data_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("wr_data_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_ctrl1_enable_q (expected: 0x0)
        reg_model.timer_ctrl1_enable_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl1_enable_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_ctrl1_enable_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_ctrl1_enable_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of bvalid_q (expected: 0x0)
        reg_model.bvalid_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read bvalid_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("bvalid_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("bvalid_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of wr_addr_q (expected: 0x0)
        reg_model.wr_addr_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read wr_addr_q: %s", status.name()))
            errors++;
        end else if (rdata !== 8'h0) begin
            `uvm_error(get_type_name(), $sformatf("wr_addr_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("wr_addr_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_ctrl1_interrupt_q (expected: 0x0)
        reg_model.timer_ctrl1_interrupt_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl1_interrupt_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_ctrl1_interrupt_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_ctrl1_interrupt_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of awvalid_q (expected: 0x0)
        reg_model.awvalid_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read awvalid_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("awvalid_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("awvalid_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_ctrl0_interrupt_q (expected: 0x0)
        reg_model.timer_ctrl0_interrupt_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl0_interrupt_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_ctrl0_interrupt_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_ctrl0_interrupt_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_ctrl0_wr_q (expected: 0x0)
        reg_model.timer_ctrl0_wr_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl0_wr_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_ctrl0_wr_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_ctrl0_wr_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_cmp1_wr_q (expected: 0x0)
        reg_model.timer_cmp1_wr_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_cmp1_wr_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_cmp1_wr_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_cmp1_wr_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer1_value_q (expected: 0x0)
        reg_model.timer1_value_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer1_value_q: %s", status.name()))
            errors++;
        end else if (rdata !== 32'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer1_value_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer1_value_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer0_value_q (expected: 0x0)
        reg_model.timer0_value_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer0_value_q: %s", status.name()))
            errors++;
        end else if (rdata !== 32'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer0_value_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer0_value_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        // Check reset value of timer_ctrl1_wr_q (expected: 0x0)
        reg_model.timer_ctrl1_wr_q.read(status, rdata);
        if (status != UVM_IS_OK) begin
            `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl1_wr_q: %s", status.name()))
            errors++;
        end else if (rdata !== 1'h0) begin
            `uvm_error(get_type_name(), $sformatf("timer_ctrl1_wr_q reset value mismatch: expected=0x%0h, got=0x%0h", 0, rdata))
            errors++;
        end else begin
            `uvm_info(get_type_name(), $sformatf("timer_ctrl1_wr_q reset value correct: 0x%0h", rdata), UVM_MEDIUM)
        end

        if (errors == 0) begin
            `uvm_info(get_type_name(), "All reset values correct!", UVM_LOW)
        end else begin
            `uvm_error(get_type_name(), $sformatf("Reset value check failed with %0d errors", errors))
        end

    endtask : body

endclass : timer_regs_regs_reset_test_seq


// ------------------------------------------------------------------------
// RAL Read-Write Test Sequence for timer_regs_regs
// ------------------------------------------------------------------------

class timer_regs_regs_rw_test_seq extends uvm_sequence;
    `uvm_object_utils(timer_regs_regs_rw_test_seq)

    timer_regs_regs_block reg_model;
    int num_iterations = 10;  // Number of random values to test

    function new(string name = "timer_regs_regs_rw_test_seq");
        super.new(name);
    endfunction : new

    task body();
        uvm_status_e status;
        uvm_reg_data_t wdata, rdata;
        int errors = 0;

        `uvm_info(get_type_name(), "Starting read-write test...", UVM_LOW)

        // Test each RW register with random values
        for (int i = 0; i < num_iterations; i++) begin
            `uvm_info(get_type_name(), $sformatf("Iteration %0d/%0d", i+1, num_iterations), UVM_MEDIUM)

            // Test timer_cmp0_value_q
            wdata = $urandom() & 32'hFFFFFFFF;
            reg_model.timer_cmp0_value_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_cmp0_value_q"))
                errors++;
            end

            reg_model.timer_cmp0_value_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_cmp0_value_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp0_value_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_cmp0_value_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test intr_q
            wdata = $urandom() & 1'h1;
            reg_model.intr_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write intr_q"))
                errors++;
            end

            reg_model.intr_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read intr_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("intr_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("intr_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_cmp1_value_q
            wdata = $urandom() & 32'hFFFFFFFF;
            reg_model.timer_cmp1_value_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_cmp1_value_q"))
                errors++;
            end

            reg_model.timer_cmp1_value_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_cmp1_value_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp1_value_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_cmp1_value_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_cmp0_wr_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_cmp0_wr_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_cmp0_wr_q"))
                errors++;
            end

            reg_model.timer_cmp0_wr_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_cmp0_wr_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp0_wr_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_cmp0_wr_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_val0_wr_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_val0_wr_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_val0_wr_q"))
                errors++;
            end

            reg_model.timer_val0_wr_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_val0_wr_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_val0_wr_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_val0_wr_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_ctrl0_enable_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_ctrl0_enable_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_ctrl0_enable_q"))
                errors++;
            end

            reg_model.timer_ctrl0_enable_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl0_enable_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_enable_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_ctrl0_enable_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test rvalid_q
            wdata = $urandom() & 1'h1;
            reg_model.rvalid_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write rvalid_q"))
                errors++;
            end

            reg_model.rvalid_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read rvalid_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("rvalid_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("rvalid_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_val1_wr_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_val1_wr_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_val1_wr_q"))
                errors++;
            end

            reg_model.timer_val1_wr_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_val1_wr_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_val1_wr_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_val1_wr_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test rd_data_q
            wdata = $urandom() & 32'hFFFFFFFF;
            reg_model.rd_data_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write rd_data_q"))
                errors++;
            end

            reg_model.rd_data_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read rd_data_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("rd_data_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("rd_data_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test wvalid_q
            wdata = $urandom() & 1'h1;
            reg_model.wvalid_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write wvalid_q"))
                errors++;
            end

            reg_model.wvalid_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read wvalid_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("wvalid_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("wvalid_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test wr_data_q
            wdata = $urandom() & 32'hFFFFFFFF;
            reg_model.wr_data_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write wr_data_q"))
                errors++;
            end

            reg_model.wr_data_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read wr_data_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("wr_data_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("wr_data_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_ctrl1_enable_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_ctrl1_enable_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_ctrl1_enable_q"))
                errors++;
            end

            reg_model.timer_ctrl1_enable_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl1_enable_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_enable_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_ctrl1_enable_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test bvalid_q
            wdata = $urandom() & 1'h1;
            reg_model.bvalid_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write bvalid_q"))
                errors++;
            end

            reg_model.bvalid_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read bvalid_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("bvalid_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("bvalid_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test wr_addr_q
            wdata = $urandom() & 8'hFF;
            reg_model.wr_addr_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write wr_addr_q"))
                errors++;
            end

            reg_model.wr_addr_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read wr_addr_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("wr_addr_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("wr_addr_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_ctrl1_interrupt_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_ctrl1_interrupt_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_ctrl1_interrupt_q"))
                errors++;
            end

            reg_model.timer_ctrl1_interrupt_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl1_interrupt_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_interrupt_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_ctrl1_interrupt_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test awvalid_q
            wdata = $urandom() & 1'h1;
            reg_model.awvalid_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write awvalid_q"))
                errors++;
            end

            reg_model.awvalid_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read awvalid_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("awvalid_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("awvalid_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_ctrl0_interrupt_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_ctrl0_interrupt_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_ctrl0_interrupt_q"))
                errors++;
            end

            reg_model.timer_ctrl0_interrupt_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl0_interrupt_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_interrupt_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_ctrl0_interrupt_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_ctrl0_wr_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_ctrl0_wr_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_ctrl0_wr_q"))
                errors++;
            end

            reg_model.timer_ctrl0_wr_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl0_wr_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_wr_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_ctrl0_wr_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_cmp1_wr_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_cmp1_wr_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_cmp1_wr_q"))
                errors++;
            end

            reg_model.timer_cmp1_wr_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_cmp1_wr_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp1_wr_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_cmp1_wr_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer1_value_q
            wdata = $urandom() & 32'hFFFFFFFF;
            reg_model.timer1_value_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer1_value_q"))
                errors++;
            end

            reg_model.timer1_value_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer1_value_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer1_value_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer1_value_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer0_value_q
            wdata = $urandom() & 32'hFFFFFFFF;
            reg_model.timer0_value_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer0_value_q"))
                errors++;
            end

            reg_model.timer0_value_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer0_value_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer0_value_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer0_value_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

            // Test timer_ctrl1_wr_q
            wdata = $urandom() & 1'h1;
            reg_model.timer_ctrl1_wr_q.write(status, wdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to write timer_ctrl1_wr_q"))
                errors++;
            end

            reg_model.timer_ctrl1_wr_q.read(status, rdata);
            if (status != UVM_IS_OK) begin
                `uvm_error(get_type_name(), $sformatf("Failed to read timer_ctrl1_wr_q"))
                errors++;
            end else if (rdata !== wdata) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_wr_q R/W mismatch: wrote=0x%0h, read=0x%0h", wdata, rdata))
                errors++;
            end else begin
                `uvm_info(get_type_name(), $sformatf("timer_ctrl1_wr_q R/W pass: 0x%0h", rdata), UVM_HIGH)
            end

        end

        if (errors == 0) begin
            `uvm_info(get_type_name(), "All R/W tests passed!", UVM_LOW)
        end else begin
            `uvm_error(get_type_name(), $sformatf("R/W test failed with %0d errors", errors))
        end

    endtask : body

endclass : timer_regs_regs_rw_test_seq


// ------------------------------------------------------------------------
// RAL Access Rights Test Sequence for timer_regs_regs
// ------------------------------------------------------------------------

class timer_regs_regs_access_test_seq extends uvm_sequence;
    `uvm_object_utils(timer_regs_regs_access_test_seq)

    timer_regs_regs_block reg_model;

    function new(string name = "timer_regs_regs_access_test_seq");
        super.new(name);
    endfunction : new

    task body();
        uvm_status_e status;
        uvm_reg_data_t wdata, rdata_before, rdata_after;
        int errors = 0;

        `uvm_info(get_type_name(), "Starting access rights test...", UVM_LOW)

        if (errors == 0) begin
            `uvm_info(get_type_name(), "All access rights tests passed!", UVM_LOW)
        end else begin
            `uvm_error(get_type_name(), $sformatf("Access rights test failed with %0d errors", errors))
        end

    endtask : body

endclass : timer_regs_regs_access_test_seq


// ------------------------------------------------------------------------
// RAL Bit Bash Test Sequence for timer_regs_regs
// Walking 1s and Walking 0s test
// ------------------------------------------------------------------------

class timer_regs_regs_bit_bash_seq extends uvm_sequence;
    `uvm_object_utils(timer_regs_regs_bit_bash_seq)

    timer_regs_regs_block reg_model;

    function new(string name = "timer_regs_regs_bit_bash_seq");
        super.new(name);
    endfunction : new

    task body();
        uvm_status_e status;
        uvm_reg_data_t wdata, rdata;
        int errors = 0;

        `uvm_info(get_type_name(), "Starting bit bash test...", UVM_LOW)

        // Bit bash test for timer_cmp0_value_q (32-bit)
        `uvm_info(get_type_name(), "Testing timer_cmp0_value_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = 32'b1 << bit;
            reg_model.timer_cmp0_value_q.write(status, wdata);
            reg_model.timer_cmp0_value_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp0_value_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = ~(32'b1 << bit);
            reg_model.timer_cmp0_value_q.write(status, wdata);
            reg_model.timer_cmp0_value_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp0_value_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for intr_q (1-bit)
        `uvm_info(get_type_name(), "Testing intr_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.intr_q.write(status, wdata);
            reg_model.intr_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("intr_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.intr_q.write(status, wdata);
            reg_model.intr_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("intr_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_cmp1_value_q (32-bit)
        `uvm_info(get_type_name(), "Testing timer_cmp1_value_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = 32'b1 << bit;
            reg_model.timer_cmp1_value_q.write(status, wdata);
            reg_model.timer_cmp1_value_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp1_value_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = ~(32'b1 << bit);
            reg_model.timer_cmp1_value_q.write(status, wdata);
            reg_model.timer_cmp1_value_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp1_value_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_cmp0_wr_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_cmp0_wr_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_cmp0_wr_q.write(status, wdata);
            reg_model.timer_cmp0_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp0_wr_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_cmp0_wr_q.write(status, wdata);
            reg_model.timer_cmp0_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp0_wr_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_val0_wr_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_val0_wr_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_val0_wr_q.write(status, wdata);
            reg_model.timer_val0_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_val0_wr_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_val0_wr_q.write(status, wdata);
            reg_model.timer_val0_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_val0_wr_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_ctrl0_enable_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_ctrl0_enable_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_ctrl0_enable_q.write(status, wdata);
            reg_model.timer_ctrl0_enable_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_enable_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_ctrl0_enable_q.write(status, wdata);
            reg_model.timer_ctrl0_enable_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_enable_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for rvalid_q (1-bit)
        `uvm_info(get_type_name(), "Testing rvalid_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.rvalid_q.write(status, wdata);
            reg_model.rvalid_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("rvalid_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.rvalid_q.write(status, wdata);
            reg_model.rvalid_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("rvalid_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_val1_wr_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_val1_wr_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_val1_wr_q.write(status, wdata);
            reg_model.timer_val1_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_val1_wr_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_val1_wr_q.write(status, wdata);
            reg_model.timer_val1_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_val1_wr_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for rd_data_q (32-bit)
        `uvm_info(get_type_name(), "Testing rd_data_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = 32'b1 << bit;
            reg_model.rd_data_q.write(status, wdata);
            reg_model.rd_data_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("rd_data_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = ~(32'b1 << bit);
            reg_model.rd_data_q.write(status, wdata);
            reg_model.rd_data_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("rd_data_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for wvalid_q (1-bit)
        `uvm_info(get_type_name(), "Testing wvalid_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.wvalid_q.write(status, wdata);
            reg_model.wvalid_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("wvalid_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.wvalid_q.write(status, wdata);
            reg_model.wvalid_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("wvalid_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for wr_data_q (32-bit)
        `uvm_info(get_type_name(), "Testing wr_data_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = 32'b1 << bit;
            reg_model.wr_data_q.write(status, wdata);
            reg_model.wr_data_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("wr_data_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = ~(32'b1 << bit);
            reg_model.wr_data_q.write(status, wdata);
            reg_model.wr_data_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("wr_data_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_ctrl1_enable_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_ctrl1_enable_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_ctrl1_enable_q.write(status, wdata);
            reg_model.timer_ctrl1_enable_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_enable_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_ctrl1_enable_q.write(status, wdata);
            reg_model.timer_ctrl1_enable_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_enable_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for bvalid_q (1-bit)
        `uvm_info(get_type_name(), "Testing bvalid_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.bvalid_q.write(status, wdata);
            reg_model.bvalid_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("bvalid_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.bvalid_q.write(status, wdata);
            reg_model.bvalid_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("bvalid_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for wr_addr_q (8-bit)
        `uvm_info(get_type_name(), "Testing wr_addr_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 8; bit++) begin
            wdata = 8'b1 << bit;
            reg_model.wr_addr_q.write(status, wdata);
            reg_model.wr_addr_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("wr_addr_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 8; bit++) begin
            wdata = ~(8'b1 << bit);
            reg_model.wr_addr_q.write(status, wdata);
            reg_model.wr_addr_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("wr_addr_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_ctrl1_interrupt_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_ctrl1_interrupt_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_ctrl1_interrupt_q.write(status, wdata);
            reg_model.timer_ctrl1_interrupt_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_interrupt_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_ctrl1_interrupt_q.write(status, wdata);
            reg_model.timer_ctrl1_interrupt_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_interrupt_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for awvalid_q (1-bit)
        `uvm_info(get_type_name(), "Testing awvalid_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.awvalid_q.write(status, wdata);
            reg_model.awvalid_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("awvalid_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.awvalid_q.write(status, wdata);
            reg_model.awvalid_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("awvalid_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_ctrl0_interrupt_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_ctrl0_interrupt_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_ctrl0_interrupt_q.write(status, wdata);
            reg_model.timer_ctrl0_interrupt_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_interrupt_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_ctrl0_interrupt_q.write(status, wdata);
            reg_model.timer_ctrl0_interrupt_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_interrupt_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_ctrl0_wr_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_ctrl0_wr_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_ctrl0_wr_q.write(status, wdata);
            reg_model.timer_ctrl0_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_wr_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_ctrl0_wr_q.write(status, wdata);
            reg_model.timer_ctrl0_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl0_wr_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_cmp1_wr_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_cmp1_wr_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_cmp1_wr_q.write(status, wdata);
            reg_model.timer_cmp1_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp1_wr_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_cmp1_wr_q.write(status, wdata);
            reg_model.timer_cmp1_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_cmp1_wr_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer1_value_q (32-bit)
        `uvm_info(get_type_name(), "Testing timer1_value_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = 32'b1 << bit;
            reg_model.timer1_value_q.write(status, wdata);
            reg_model.timer1_value_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer1_value_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = ~(32'b1 << bit);
            reg_model.timer1_value_q.write(status, wdata);
            reg_model.timer1_value_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer1_value_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer0_value_q (32-bit)
        `uvm_info(get_type_name(), "Testing timer0_value_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = 32'b1 << bit;
            reg_model.timer0_value_q.write(status, wdata);
            reg_model.timer0_value_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer0_value_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 32; bit++) begin
            wdata = ~(32'b1 << bit);
            reg_model.timer0_value_q.write(status, wdata);
            reg_model.timer0_value_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer0_value_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        // Bit bash test for timer_ctrl1_wr_q (1-bit)
        `uvm_info(get_type_name(), "Testing timer_ctrl1_wr_q...", UVM_MEDIUM)

        // Walking 1s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = 1'b1 << bit;
            reg_model.timer_ctrl1_wr_q.write(status, wdata);
            reg_model.timer_ctrl1_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b1) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_wr_q[%0d] stuck at 0", bit))
                errors++;
            end
        end

        // Walking 0s test
        for (int bit = 0; bit < 1; bit++) begin
            wdata = ~(1'b1 << bit);
            reg_model.timer_ctrl1_wr_q.write(status, wdata);
            reg_model.timer_ctrl1_wr_q.read(status, rdata);
            if (rdata[bit] !== 1'b0) begin
                `uvm_error(get_type_name(), $sformatf("timer_ctrl1_wr_q[%0d] stuck at 1", bit))
                errors++;
            end
        end

        if (errors == 0) begin
            `uvm_info(get_type_name(), "All bit bash tests passed!", UVM_LOW)
        end else begin
            `uvm_error(get_type_name(), $sformatf("Bit bash test failed with %0d errors", errors))
        end

    endtask : body

endclass : timer_regs_regs_bit_bash_seq


endpackage : timer_regs_regs_ral_test_pkg
