// ------------------------------------------------------------------------
// RAL Package: timer_regs_regs_ral_pkg
// Auto-generated by AutoUVM RAL Generator
// ------------------------------------------------------------------------

package timer_regs_regs_ral_pkg;

    import uvm_pkg::*;
    `include "uvm_macros.svh"

    // Register: timer1_value_q @ 0x0000

    class timer1_value_q_reg extends uvm_reg;
        `uvm_object_utils(timer1_value_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer1_value_q_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [31:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(32),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer1_value_q_reg

    // Register: bvalid_q @ 0x0004

    class bvalid_q_reg extends uvm_reg;
        `uvm_object_utils(bvalid_q_reg)

        rand uvm_reg_field data;

        function new(string name = "bvalid_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : bvalid_q_reg

    // Register: timer_ctrl1_interrupt_q @ 0x0008

    class timer_ctrl1_interrupt_q_reg extends uvm_reg;
        `uvm_object_utils(timer_ctrl1_interrupt_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_ctrl1_interrupt_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_ctrl1_interrupt_q_reg

    // Register: timer_cmp0_wr_q @ 0x000C

    class timer_cmp0_wr_q_reg extends uvm_reg;
        `uvm_object_utils(timer_cmp0_wr_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_cmp0_wr_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_cmp0_wr_q_reg

    // Register: timer_cmp1_wr_q @ 0x0010

    class timer_cmp1_wr_q_reg extends uvm_reg;
        `uvm_object_utils(timer_cmp1_wr_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_cmp1_wr_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_cmp1_wr_q_reg

    // Register: rvalid_q @ 0x0014

    class rvalid_q_reg extends uvm_reg;
        `uvm_object_utils(rvalid_q_reg)

        rand uvm_reg_field data;

        function new(string name = "rvalid_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : rvalid_q_reg

    // Register: timer_ctrl0_wr_q @ 0x0018

    class timer_ctrl0_wr_q_reg extends uvm_reg;
        `uvm_object_utils(timer_ctrl0_wr_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_ctrl0_wr_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_ctrl0_wr_q_reg

    // Register: timer_ctrl0_interrupt_q @ 0x001C

    class timer_ctrl0_interrupt_q_reg extends uvm_reg;
        `uvm_object_utils(timer_ctrl0_interrupt_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_ctrl0_interrupt_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_ctrl0_interrupt_q_reg

    // Register: timer_ctrl0_enable_q @ 0x0020

    class timer_ctrl0_enable_q_reg extends uvm_reg;
        `uvm_object_utils(timer_ctrl0_enable_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_ctrl0_enable_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_ctrl0_enable_q_reg

    // Register: timer0_value_q @ 0x0024

    class timer0_value_q_reg extends uvm_reg;
        `uvm_object_utils(timer0_value_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer0_value_q_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [31:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(32),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer0_value_q_reg

    // Register: awvalid_q @ 0x0028

    class awvalid_q_reg extends uvm_reg;
        `uvm_object_utils(awvalid_q_reg)

        rand uvm_reg_field data;

        function new(string name = "awvalid_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : awvalid_q_reg

    // Register: timer_ctrl1_wr_q @ 0x002C

    class timer_ctrl1_wr_q_reg extends uvm_reg;
        `uvm_object_utils(timer_ctrl1_wr_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_ctrl1_wr_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_ctrl1_wr_q_reg

    // Register: timer_cmp0_value_q @ 0x0030

    class timer_cmp0_value_q_reg extends uvm_reg;
        `uvm_object_utils(timer_cmp0_value_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_cmp0_value_q_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [31:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(32),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_cmp0_value_q_reg

    // Register: wr_data_q @ 0x0034

    class wr_data_q_reg extends uvm_reg;
        `uvm_object_utils(wr_data_q_reg)

        rand uvm_reg_field data;

        function new(string name = "wr_data_q_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [31:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(32),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : wr_data_q_reg

    // Register: wvalid_q @ 0x0038

    class wvalid_q_reg extends uvm_reg;
        `uvm_object_utils(wvalid_q_reg)

        rand uvm_reg_field data;

        function new(string name = "wvalid_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : wvalid_q_reg

    // Register: timer_val1_wr_q @ 0x003C

    class timer_val1_wr_q_reg extends uvm_reg;
        `uvm_object_utils(timer_val1_wr_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_val1_wr_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_val1_wr_q_reg

    // Register: rd_data_q @ 0x0040

    class rd_data_q_reg extends uvm_reg;
        `uvm_object_utils(rd_data_q_reg)

        rand uvm_reg_field data;

        function new(string name = "rd_data_q_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [31:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(32),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : rd_data_q_reg

    // Register: timer_val0_wr_q @ 0x0044

    class timer_val0_wr_q_reg extends uvm_reg;
        `uvm_object_utils(timer_val0_wr_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_val0_wr_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_val0_wr_q_reg

    // Register: timer_ctrl1_enable_q @ 0x0048

    class timer_ctrl1_enable_q_reg extends uvm_reg;
        `uvm_object_utils(timer_ctrl1_enable_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_ctrl1_enable_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_ctrl1_enable_q_reg

    // Register: timer_cmp1_value_q @ 0x004C

    class timer_cmp1_value_q_reg extends uvm_reg;
        `uvm_object_utils(timer_cmp1_value_q_reg)

        rand uvm_reg_field data;

        function new(string name = "timer_cmp1_value_q_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [31:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(32),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : timer_cmp1_value_q_reg

    // Register: intr_q @ 0x0050

    class intr_q_reg extends uvm_reg;
        `uvm_object_utils(intr_q_reg)

        rand uvm_reg_field data;

        function new(string name = "intr_q_reg");
            super.new(name, 1, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [0:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(1),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : intr_q_reg

    // Register: wr_addr_q @ 0x0054

    class wr_addr_q_reg extends uvm_reg;
        `uvm_object_utils(wr_addr_q_reg)

        rand uvm_reg_field data;

        function new(string name = "wr_addr_q_reg");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Field: data [7:0]
            data = uvm_reg_field::type_id::create("data");
            data.configure(
                .parent(this),
                .size(8),
                .lsb_pos(0),
                .access("RW"),
                .volatile(0),
                .reset(0),
                .has_reset(1),
                .is_rand(1),
                .individually_accessible(1)
            );

        endfunction : build

    endclass : wr_addr_q_reg

    // Register Block: timer_regs_regs
    // Base Address: 0x00000000
    // Registers extracted from timer_regs
    class timer_regs_regs_block extends uvm_reg_block;
        `uvm_object_utils(timer_regs_regs_block)

        rand timer1_value_q_reg timer1_value_q;
        rand bvalid_q_reg bvalid_q;
        rand timer_ctrl1_interrupt_q_reg timer_ctrl1_interrupt_q;
        rand timer_cmp0_wr_q_reg timer_cmp0_wr_q;
        rand timer_cmp1_wr_q_reg timer_cmp1_wr_q;
        rand rvalid_q_reg rvalid_q;
        rand timer_ctrl0_wr_q_reg timer_ctrl0_wr_q;
        rand timer_ctrl0_interrupt_q_reg timer_ctrl0_interrupt_q;
        rand timer_ctrl0_enable_q_reg timer_ctrl0_enable_q;
        rand timer0_value_q_reg timer0_value_q;
        rand awvalid_q_reg awvalid_q;
        rand timer_ctrl1_wr_q_reg timer_ctrl1_wr_q;
        rand timer_cmp0_value_q_reg timer_cmp0_value_q;
        rand wr_data_q_reg wr_data_q;
        rand wvalid_q_reg wvalid_q;
        rand timer_val1_wr_q_reg timer_val1_wr_q;
        rand rd_data_q_reg rd_data_q;
        rand timer_val0_wr_q_reg timer_val0_wr_q;
        rand timer_ctrl1_enable_q_reg timer_ctrl1_enable_q;
        rand timer_cmp1_value_q_reg timer_cmp1_value_q;
        rand intr_q_reg intr_q;
        rand wr_addr_q_reg wr_addr_q;

        function new(string name = "timer_regs_regs_block");
            super.new(name, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            // Create default register map
            default_map = create_map(
                .name("default_map"),
                .base_addr(0),
                .n_bytes(4),
                .endian(UVM_LITTLE_ENDIAN)
            );

            // Register: timer1_value_q @ 0x0000
            timer1_value_q = timer1_value_q_reg::type_id::create("timer1_value_q");
            timer1_value_q.configure(this, null, "");
            timer1_value_q.build();
            default_map.add_reg(
                .rg(timer1_value_q),
                .offset(0),
                .rights("RW")
            );

            // Register: bvalid_q @ 0x0004
            bvalid_q = bvalid_q_reg::type_id::create("bvalid_q");
            bvalid_q.configure(this, null, "");
            bvalid_q.build();
            default_map.add_reg(
                .rg(bvalid_q),
                .offset(4),
                .rights("RW")
            );

            // Register: timer_ctrl1_interrupt_q @ 0x0008
            timer_ctrl1_interrupt_q = timer_ctrl1_interrupt_q_reg::type_id::create("timer_ctrl1_interrupt_q");
            timer_ctrl1_interrupt_q.configure(this, null, "");
            timer_ctrl1_interrupt_q.build();
            default_map.add_reg(
                .rg(timer_ctrl1_interrupt_q),
                .offset(8),
                .rights("RW")
            );

            // Register: timer_cmp0_wr_q @ 0x000C
            timer_cmp0_wr_q = timer_cmp0_wr_q_reg::type_id::create("timer_cmp0_wr_q");
            timer_cmp0_wr_q.configure(this, null, "");
            timer_cmp0_wr_q.build();
            default_map.add_reg(
                .rg(timer_cmp0_wr_q),
                .offset(12),
                .rights("RW")
            );

            // Register: timer_cmp1_wr_q @ 0x0010
            timer_cmp1_wr_q = timer_cmp1_wr_q_reg::type_id::create("timer_cmp1_wr_q");
            timer_cmp1_wr_q.configure(this, null, "");
            timer_cmp1_wr_q.build();
            default_map.add_reg(
                .rg(timer_cmp1_wr_q),
                .offset(16),
                .rights("RW")
            );

            // Register: rvalid_q @ 0x0014
            rvalid_q = rvalid_q_reg::type_id::create("rvalid_q");
            rvalid_q.configure(this, null, "");
            rvalid_q.build();
            default_map.add_reg(
                .rg(rvalid_q),
                .offset(20),
                .rights("RW")
            );

            // Register: timer_ctrl0_wr_q @ 0x0018
            timer_ctrl0_wr_q = timer_ctrl0_wr_q_reg::type_id::create("timer_ctrl0_wr_q");
            timer_ctrl0_wr_q.configure(this, null, "");
            timer_ctrl0_wr_q.build();
            default_map.add_reg(
                .rg(timer_ctrl0_wr_q),
                .offset(24),
                .rights("RW")
            );

            // Register: timer_ctrl0_interrupt_q @ 0x001C
            timer_ctrl0_interrupt_q = timer_ctrl0_interrupt_q_reg::type_id::create("timer_ctrl0_interrupt_q");
            timer_ctrl0_interrupt_q.configure(this, null, "");
            timer_ctrl0_interrupt_q.build();
            default_map.add_reg(
                .rg(timer_ctrl0_interrupt_q),
                .offset(28),
                .rights("RW")
            );

            // Register: timer_ctrl0_enable_q @ 0x0020
            timer_ctrl0_enable_q = timer_ctrl0_enable_q_reg::type_id::create("timer_ctrl0_enable_q");
            timer_ctrl0_enable_q.configure(this, null, "");
            timer_ctrl0_enable_q.build();
            default_map.add_reg(
                .rg(timer_ctrl0_enable_q),
                .offset(32),
                .rights("RW")
            );

            // Register: timer0_value_q @ 0x0024
            timer0_value_q = timer0_value_q_reg::type_id::create("timer0_value_q");
            timer0_value_q.configure(this, null, "");
            timer0_value_q.build();
            default_map.add_reg(
                .rg(timer0_value_q),
                .offset(36),
                .rights("RW")
            );

            // Register: awvalid_q @ 0x0028
            awvalid_q = awvalid_q_reg::type_id::create("awvalid_q");
            awvalid_q.configure(this, null, "");
            awvalid_q.build();
            default_map.add_reg(
                .rg(awvalid_q),
                .offset(40),
                .rights("RW")
            );

            // Register: timer_ctrl1_wr_q @ 0x002C
            timer_ctrl1_wr_q = timer_ctrl1_wr_q_reg::type_id::create("timer_ctrl1_wr_q");
            timer_ctrl1_wr_q.configure(this, null, "");
            timer_ctrl1_wr_q.build();
            default_map.add_reg(
                .rg(timer_ctrl1_wr_q),
                .offset(44),
                .rights("RW")
            );

            // Register: timer_cmp0_value_q @ 0x0030
            timer_cmp0_value_q = timer_cmp0_value_q_reg::type_id::create("timer_cmp0_value_q");
            timer_cmp0_value_q.configure(this, null, "");
            timer_cmp0_value_q.build();
            default_map.add_reg(
                .rg(timer_cmp0_value_q),
                .offset(48),
                .rights("RW")
            );

            // Register: wr_data_q @ 0x0034
            wr_data_q = wr_data_q_reg::type_id::create("wr_data_q");
            wr_data_q.configure(this, null, "");
            wr_data_q.build();
            default_map.add_reg(
                .rg(wr_data_q),
                .offset(52),
                .rights("RW")
            );

            // Register: wvalid_q @ 0x0038
            wvalid_q = wvalid_q_reg::type_id::create("wvalid_q");
            wvalid_q.configure(this, null, "");
            wvalid_q.build();
            default_map.add_reg(
                .rg(wvalid_q),
                .offset(56),
                .rights("RW")
            );

            // Register: timer_val1_wr_q @ 0x003C
            timer_val1_wr_q = timer_val1_wr_q_reg::type_id::create("timer_val1_wr_q");
            timer_val1_wr_q.configure(this, null, "");
            timer_val1_wr_q.build();
            default_map.add_reg(
                .rg(timer_val1_wr_q),
                .offset(60),
                .rights("RW")
            );

            // Register: rd_data_q @ 0x0040
            rd_data_q = rd_data_q_reg::type_id::create("rd_data_q");
            rd_data_q.configure(this, null, "");
            rd_data_q.build();
            default_map.add_reg(
                .rg(rd_data_q),
                .offset(64),
                .rights("RW")
            );

            // Register: timer_val0_wr_q @ 0x0044
            timer_val0_wr_q = timer_val0_wr_q_reg::type_id::create("timer_val0_wr_q");
            timer_val0_wr_q.configure(this, null, "");
            timer_val0_wr_q.build();
            default_map.add_reg(
                .rg(timer_val0_wr_q),
                .offset(68),
                .rights("RW")
            );

            // Register: timer_ctrl1_enable_q @ 0x0048
            timer_ctrl1_enable_q = timer_ctrl1_enable_q_reg::type_id::create("timer_ctrl1_enable_q");
            timer_ctrl1_enable_q.configure(this, null, "");
            timer_ctrl1_enable_q.build();
            default_map.add_reg(
                .rg(timer_ctrl1_enable_q),
                .offset(72),
                .rights("RW")
            );

            // Register: timer_cmp1_value_q @ 0x004C
            timer_cmp1_value_q = timer_cmp1_value_q_reg::type_id::create("timer_cmp1_value_q");
            timer_cmp1_value_q.configure(this, null, "");
            timer_cmp1_value_q.build();
            default_map.add_reg(
                .rg(timer_cmp1_value_q),
                .offset(76),
                .rights("RW")
            );

            // Register: intr_q @ 0x0050
            intr_q = intr_q_reg::type_id::create("intr_q");
            intr_q.configure(this, null, "");
            intr_q.build();
            default_map.add_reg(
                .rg(intr_q),
                .offset(80),
                .rights("RW")
            );

            // Register: wr_addr_q @ 0x0054
            wr_addr_q = wr_addr_q_reg::type_id::create("wr_addr_q");
            wr_addr_q.configure(this, null, "");
            wr_addr_q.build();
            default_map.add_reg(
                .rg(wr_addr_q),
                .offset(84),
                .rights("RW")
            );

            // Lock the model
            lock_model();
        endfunction : build

    endclass : timer_regs_regs_block

endpackage : timer_regs_regs_ral_pkg
